# Sample workflow for scanning a target with Snyk API & Web
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # - name: Scan with Snyk API & Web
      #   id: snyk-scan
      #   uses: Probely/probely-github-action@main
      #   with:
      #     api-key: ${{ secrets.PROBELY_API_KEY }}
      #     target-id: "44xb2GZVa1oh"
      #     region: "us"
      #     scan-profile: "lightning"
      # - name: Install Probely
      #   run: pip install probely
      # - name: Blocking Scan with Probely
      #   run: probely targets follow-scan --output JSON --severity-threshold CRITICAL --api-key ${{ secrets.PROBELY_API_KEY }} 44xb2GZVa1oh
      - name: Run Probely scan gate
        uses: gwnlng/snyk-probely-gate-action/.github/actions/snyk-probely-gate
        with:
          mode: follow-scan
          target_id: "44xb2GZVa1oh"
          severity-threshold: LOW
          timeout: '60'
          fail-immediately: 'false'
        env:
          PROBELY_API_KEY: ${{ secrets.PROBELY_API_KEY }}
